-- Migration: Create ml_trade_outcomes table for PostgreSQL
-- Date: 2026-01-17
-- Description: Table for ML feature collection and trade analysis (80+ features)

CREATE TABLE IF NOT EXISTS ml_trade_outcomes (
    id SERIAL PRIMARY KEY,
    trade_id TEXT,
    symbol TEXT NOT NULL,
    exchange TEXT DEFAULT 'mexc',
    workspace_id INTEGER DEFAULT 1,
    entry_time TIMESTAMP WITH TIME ZONE,
    entry_price NUMERIC,
    entry_qty NUMERIC,
    entry_side TEXT,
    spread_bps_entry NUMERIC,
    eff_spread_bps_entry NUMERIC,
    depth5_bid_usd_entry NUMERIC,
    depth5_ask_usd_entry NUMERIC,
    depth10_bid_usd_entry NUMERIC,
    depth10_ask_usd_entry NUMERIC,
    imbalance_entry NUMERIC,
    atr1m_pct_entry NUMERIC,
    grinder_ratio_entry NUMERIC,
    pullback_median_retrace_entry NUMERIC,
    trades_per_min_entry NUMERIC,
    usd_per_min_entry NUMERIC,
    median_trade_usd_entry NUMERIC,
    spread_pct_entry NUMERIC,
    spread_abs_entry NUMERIC,
    eff_spread_pct_entry NUMERIC,
    eff_spread_abs_entry NUMERIC,
    eff_spread_maker_bps_entry NUMERIC,
    eff_spread_taker_bps_entry NUMERIC,
    base_volume_24h_entry NUMERIC,
    quote_volume_24h_entry NUMERIC,
    maker_fee_entry NUMERIC,
    taker_fee_entry NUMERIC,
    zero_fee_entry INTEGER,
    spike_count_90m_entry INTEGER,
    range_stable_pct_entry NUMERIC,
    vol_pattern_entry INTEGER,
    dca_potential_entry INTEGER,
    scanner_score_entry NUMERIC,
    ws_lag_ms_entry INTEGER,
    depth_imbalance_entry NUMERIC,
    depth5_total_usd_entry NUMERIC,
    depth10_total_usd_entry NUMERIC,
    depth_ratio_5_to_10_entry NUMERIC,
    spread_to_depth5_ratio_entry NUMERIC,
    volume_to_depth_ratio_entry NUMERIC,
    trades_per_dollar_entry NUMERIC,
    avg_trade_size_entry NUMERIC,
    mid_price_entry NUMERIC,
    price_precision_entry INTEGER,
    spoofing_score_entry NUMERIC,
    spread_stability_entry NUMERIC,
    order_lifetime_avg_entry NUMERIC,
    book_refresh_rate_entry NUMERIC,
    mm_detected_entry INTEGER,
    mm_confidence_entry NUMERIC,
    mm_safe_size_entry NUMERIC,
    mm_lower_bound_entry NUMERIC,
    mm_upper_bound_entry NUMERIC,
    hour_of_day INTEGER,
    day_of_week INTEGER,
    minute_of_hour INTEGER,
    take_profit_bps NUMERIC,
    stop_loss_bps NUMERIC,
    trailing_stop_enabled INTEGER,
    trail_activation_bps NUMERIC,
    trail_distance_bps NUMERIC,
    timeout_seconds NUMERIC,
    exploration_mode INTEGER,
    exit_time TIMESTAMP WITH TIME ZONE,
    exit_price NUMERIC,
    exit_qty NUMERIC,
    exit_reason TEXT,
    pnl_usd NUMERIC,
    pnl_bps NUMERIC,
    pnl_percent NUMERIC,
    hold_duration_sec NUMERIC,
    max_favorable_excursion_bps NUMERIC,
    max_adverse_excursion_bps NUMERIC,
    peak_price NUMERIC,
    lowest_price NUMERIC,
    win INTEGER,
    hit_tp INTEGER,
    hit_sl INTEGER,
    hit_trailing INTEGER,
    timed_out INTEGER,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);